### ISSUE TITLE
Add `dispatch` to the effects arguments

### ISSUE THREAD

**Issue by smeijer** [davidkpiano/useEffectReducer#2]
Forked from: https://twitter.com/meijer_s/status/1252252222500622336?s=20

I think it makes sense to pass `dispatch` to the effect's arguments as well, so that we don't need to declare our effects, or "api" within the scope of the component. 

I believe this would also benefit the test-ability of the effects. As I could now just test `api` and stub `dispatch` with `jest.fn`.

```jsx
const api = {
  fetchDog: async (state, effect, dispatch) => {
    try {
      const data = await fetchRandomDog();
      dispatch({ type: 'RESOLVE', data });
    } catch (error) {
      dispatch({ type: 'REJECT', error });
    }
  },
};

function dogReducer(state, event, exec) {}
const initialState = {};

function DogFetcher() {
  const [state, dispatch] = useEffectReducer(dogReducer, initialState, api);

  // ...
}
```

**Comment by tannerlinsley** [comment]
Yeah, this will be great!
