### ISSUE TITLE
Unconditionally flushing effects is unsafe

### ISSUE THREAD

**Issue by billyjanitsch** [davidkpiano/useEffectReducer#3]
Hi! This implementation has a bug that can cause effects to be permanently skipped.

The special flush event clears all pending effects from the queue:

https://github.com/davidkpiano/useEffectReducer/blob/17da4f985366ca8d1224e2637f15b7d4acd7f69a/src/index.tsx#L72-L75

This seems fine because event is dispatched after clearing all effects in the queue:

https://github.com/davidkpiano/useEffectReducer/blob/17da4f985366ca8d1224e2637f15b7d4acd7f69a/src/index.tsx#L92-L94

https://github.com/davidkpiano/useEffectReducer/blob/17da4f985366ca8d1224e2637f15b7d4acd7f69a/src/index.tsx#L116

The problem is that this effect closes over `stateEffectTuples`. It's possible that new effects will be added to the queue in between the render and the execution of the effect. These effects won't be executed in the effect because of the closure, but they _will_ be cleared by the flush event. So they will effectively be skipped.

[Here](https://codesandbox.io/s/useeffectreducer-flush-bug-hpm90?file=/src/index.js)'s a sandbox demonstrating the problem. Click "increment" and notice that the state correctly updates to `2`, but the console has only printed `INC 0`. We'd expect it to also print `INC 1`. The latter effect was skipped because the second increment was added to the queue after the closure but before the dispatch of the flush event. So the effect gets added to the queue and then cleared without having a chance to run.

One potential solution would be to slice off the first `stateEffectTuples.length` elements from the state at the time of the update rather than unconditionally returning `[]`. Essentially this is saying "flush the effects that were just run" rather than "flush all effects".

**Comment by davidkpiano** [comment]
Can you make a failing test for this issue? Or better yet, a PR?

Otherwise I'll get to this soon.
