### ISSUE TITLE
[Question] How to “inject” dynamic dependencies within effects?

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/useEffectReducer#31]
I'm wondering if it's ok to call dynamic dependencies within effects:

```js
const history = useHistory()
const queryClient = useQueryClient()

const [state, dispatch] = useEffectReducer(reducer, initialState, {
  invalidateUsers: () => queryClient.invalidateQueries("users"),
  redirectToHome: () => history.push("/")
})
```

Let's suppose that history and queryClient will keep changing between rerenders, is my service implementation going to work?

**Comment by davidkpiano** [comment]
I believe it should, have you tried it out?

**Comment by hnordt** [comment]
Not yet, just wondering if that’s something you wanted to support/recommend

**Comment by hnordt** [comment]
Seems to work!
