### ISSUE TITLE
Can we expect useEffectReducer to work with react 18?

### ISSUE THREAD

**Issue by rodrigofariow** [davidkpiano/useEffectReducer#39]
Hey @davidkpiano !

First of all, thank you for this awesome reducer! It's the perfect approach for me and my team right now without getting 100% into xstate (yet).

Anyways, we are planning on upgrading to react 18 soon and I would like to know if I can count on not having effects running multiple times (due to the whole Strict Mode thing).
Don't know if you have tested `useEffectReducer` with it yet, but if you did, I was hoping to know your results 🙏 

Thank you for your time!

**Comment by davidkpiano** [comment]
Hey, unfortunately I haven't reworked this for React 18 (yet), but due to the nature of `useEffect`, it is still very possible that effects will double execute on first render.

**Comment by rodrigofariow** [comment]
Hello, 
Thanks for the quick reply! 🙏
