### ISSUE TITLE
Future Updates / Improvements?

### ISSUE THREAD

**Issue by aarr0n** [davidkpiano/useEffectReducer#45]
Hello,

I've noticed that the last update to this package was some 3 years ago and that was to the README, with any other change outside of this occurring 4 years ago. Given this and issues being raised such as [React 18 support](https://github.com/davidkpiano/useEffectReducer/issues/39) I'm wondering if there are any planned updates or improvements? Currently it looks as if the package is not being maintained.

Thanks!

**Comment by davidkpiano** [comment]
You're right; the package is not being maintained and I should label it as such. `useEffect` isn't the best place to execute the kind of effects I wanted to execute with this library.
